spring:
  application:
    name: final-application

  datasource:
    url: jdbc:mysql://localhost:3306/fortium_db?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true